"""Datasource metadata introspection.

Retrieves comprehensive field metadata for a selected datasource LUID by
orchestrating up to three API calls:

1. VDS ``readMetadata`` (primary — fatal on failure)
2. VDS ``getDatasourceModel`` (optional — skip on 404/non-2xx)
3. Metadata API GraphQL enrichment (optional — skip on any failure)

Sync transport using http.client (stdlib). No external HTTP dependencies.
Pure functional API — no temp I/O, no stdout printing.
"""

from __future__ import annotations

import http.client
import json
import logging
import socket
import ssl
from typing import Any
from urllib.parse import urlparse

from query_tableau_data_py.config import SdkConfig
from query_tableau_data_py.errors import IntrospectionError
from query_tableau_data_py.models import (
    AnyValueParameter,
    DatasourceModel,
    DatasourceParameter,
    DatasourceSchema,
    FieldGroup,
    FieldMeta,
    ListParameter,
    LogicalTable,
    LogicalTableRelationship,
    QuantitativeDateParameter,
    QuantitativeRangeParameter,
)
from query_tableau_data_py.modules.auth import AuthToken

logger = logging.getLogger(__name__)

_READ_METADATA_PATH = "/api/v1/vizql-data-service/read-metadata"
_GET_DATASOURCE_MODEL_PATH = "/api/v1/vizql-data-service/get-datasource-model"
_GRAPHQL_PATH = "/api/metadata/graphql"

_GRAPHQL_FIELD_INFO_QUERY = """
query DatasourceFieldInfo($luid: String!) {
  publishedDatasources(filter: { luid: $luid }) {
    name
    description
    owner {
      name
    }
    fields {
      name
      isHidden
      description
      descriptionInherited {
        attribute
        value
      }
      fullyQualifiedName
      __typename
      upstreamTables {
        name
      }
      ... on AnalyticsField {
        __typename
      }
      ... on ColumnField {
        dataCategory
        role
        dataType
        defaultFormat
        semanticRole
        aggregation
        aggregationParam
      }
      ... on CalculatedField {
        dataCategory
        role
        dataType
        defaultFormat
        semanticRole
        aggregation
        aggregationParam
        formula
        isAutoGenerated
        hasUserReference
      }
      ... on BinField {
        dataCategory
        role
        dataType
        formula
        binSize
      }
      ... on GroupField {
        dataCategory
        role
        dataType
        hasOther
      }
      ... on CombinedSetField {
        delimiter
        combinationType
      }
    }
  }
}
"""

# GraphQL-specific timeout (seconds)
_GRAPHQL_TIMEOUT = 15.0


def _make_connection(config: SdkConfig) -> http.client.HTTPSConnection:
    """Create an HTTPSConnection from SDK config."""
    parsed = urlparse(config.base_url)
    host = parsed.hostname
    port = parsed.port or 443

    if config.ssl_verify:
        ssl_context = ssl.create_default_context()
    else:
        ssl_context = ssl._create_unverified_context()

    return http.client.HTTPSConnection(
        host, port, context=ssl_context, timeout=config.timeout
    )


def _get_base_path(config: SdkConfig) -> str:
    """Extract the base path from config.base_url (for subpath installs)."""
    parsed = urlparse(config.base_url)
    return parsed.path.rstrip("/")


# ── Parameter parsing helpers ──────────────────────────────────────────────


def _parse_parameter(raw: dict[str, Any]) -> DatasourceParameter:
    """Map a raw VDS parameter dict (camelCase) to a typed Pydantic model."""
    ptype = raw.get("parameterType", "ANY_VALUE")
    base = {
        "parameter_caption": raw.get("parameterCaption", ""),
        "data_type": raw.get("dataType", ""),
        "parameter_name": raw.get("parameterName"),
        "value": raw.get("value"),
    }

    if ptype == "ANY_VALUE":
        return AnyValueParameter(parameter_type="ANY_VALUE", **base)
    if ptype == "LIST":
        return ListParameter(
            parameter_type="LIST",
            members=raw.get("members", []),
            **base,
        )
    if ptype == "QUANTITATIVE_DATE":
        return QuantitativeDateParameter(
            parameter_type="QUANTITATIVE_DATE",
            value=raw.get("value"),
            min_date=raw.get("minDate"),
            max_date=raw.get("maxDate"),
            period_value=raw.get("periodValue"),
            period_type=raw.get("periodType"),
            **{k: v for k, v in base.items() if k != "value"},
        )
    if ptype == "QUANTITATIVE_RANGE":
        return QuantitativeRangeParameter(
            parameter_type="QUANTITATIVE_RANGE",
            value=raw.get("value"),
            min=raw.get("min"),
            max=raw.get("max"),
            step=raw.get("step"),
            **{k: v for k, v in base.items() if k != "value"},
        )

    # Unknown parameter type — fall back to ANY_VALUE so the agent still gets data
    logger.warning("Unknown parameterType %r; treating as ANY_VALUE.", ptype)
    return AnyValueParameter(parameter_type="ANY_VALUE", **base)


# ── VDS API calls ────────────────────────────────────────────────────────────


def _call_read_metadata(
    config: SdkConfig,
    token: AuthToken,
    conn: http.client.HTTPSConnection,
    luid: str,
) -> dict[str, Any]:
    """POST VDS ``read-metadata``. Non-2xx raises ``IntrospectionError``."""
    base_path = _get_base_path(config)
    path = f"{base_path}{_READ_METADATA_PATH}"
    payload = {"datasource": {"datasourceLuid": luid}}
    body = json.dumps(payload).encode("utf-8")
    headers = {
        "X-Tableau-Auth": token.token,
        "Content-Type": "application/json",
        "Content-Length": str(len(body)),
    }

    try:
        conn.request("POST", path, body=body, headers=headers)
        resp = conn.getresponse()
        resp_body = resp.read()
    except socket.timeout as exc:
        raise IntrospectionError(
            status_code=None,
            response_body=b"",
            tableau_error_code=None,
            tableau_error_message=f"readMetadata timed out: {exc}",
        ) from exc
    except (http.client.HTTPException, OSError) as exc:
        raise IntrospectionError(
            status_code=None,
            response_body=b"",
            tableau_error_code=None,
            tableau_error_message=f"readMetadata transport error: {exc}",
        ) from exc

    if resp.status >= 400:
        code = None
        message = None
        try:
            data = json.loads(resp_body.decode("utf-8"))
            if isinstance(data, dict):
                error = data.get("error", {})
                if isinstance(error, dict):
                    code = str(error.get("code", "")) or None
                    message = error.get("message") or None
                else:
                    message = str(error)
        except Exception:
            message = resp_body.decode("utf-8", errors="replace") or None

        raise IntrospectionError(
            status_code=resp.status,
            response_body=resp_body,
            tableau_error_code=code,
            tableau_error_message=message or f"HTTP {resp.status}",
        )

    try:
        return json.loads(resp_body.decode("utf-8"))
    except Exception as exc:
        raise IntrospectionError(
            status_code=resp.status,
            response_body=resp_body,
            tableau_error_code=None,
            tableau_error_message=f"readMetadata response was not valid JSON: {exc}",
        ) from exc


def _call_get_datasource_model(
    config: SdkConfig,
    token: AuthToken,
    conn: http.client.HTTPSConnection,
    luid: str,
) -> dict[str, Any] | None:
    """POST VDS ``get-datasource-model``. Returns ``None`` on 404 or any non-2xx."""
    base_path = _get_base_path(config)
    path = f"{base_path}{_GET_DATASOURCE_MODEL_PATH}"
    payload = {"datasource": {"datasourceLuid": luid}}
    body = json.dumps(payload).encode("utf-8")
    headers = {
        "X-Tableau-Auth": token.token,
        "Content-Type": "application/json",
        "Content-Length": str(len(body)),
    }

    try:
        conn.request("POST", path, body=body, headers=headers)
        resp = conn.getresponse()
        resp_body = resp.read()
    except socket.timeout:
        logger.warning("getDatasourceModel timed out; skipping.")
        return None
    except (http.client.HTTPException, OSError) as exc:
        logger.warning("getDatasourceModel transport error (%s); skipping.", exc)
        return None

    if resp.status == 404:
        logger.debug(
            "getDatasourceModel returned 404; skipping (older Tableau version)."
        )
        return None

    if resp.status >= 400:
        logger.debug(
            "getDatasourceModel returned %d; skipping "
            "(requires Tableau >= 2025.3, see LIMITATIONS.md).",
            resp.status,
        )
        return None

    try:
        return json.loads(resp_body.decode("utf-8"))
    except Exception:
        logger.warning("getDatasourceModel response was not valid JSON; skipping.")
        return None


def _call_graphql_enrichment(
    config: SdkConfig,
    token: AuthToken,
    conn: http.client.HTTPSConnection,
    luid: str,
) -> dict[str, Any] | None:
    """POST Metadata API GraphQL for field enrichment. Returns ``None`` on any failure."""
    base_path = _get_base_path(config)
    path = f"{base_path}{_GRAPHQL_PATH}"
    payload = {
        "query": _GRAPHQL_FIELD_INFO_QUERY,
        "variables": {"luid": luid},
    }
    body = json.dumps(payload).encode("utf-8")
    headers = {
        "X-Tableau-Auth": token.token,
        "Content-Type": "application/json",
        "Content-Length": str(len(body)),
    }

    try:
        # Apply GraphQL-specific timeout
        if conn.sock is not None:
            conn.sock.settimeout(_GRAPHQL_TIMEOUT)
        conn.request("POST", path, body=body, headers=headers)
        resp = conn.getresponse()
        resp_body = resp.read()
    except socket.timeout:
        logger.warning("GraphQL enrichment timed out; skipping.")
        return None
    except (http.client.HTTPException, OSError) as exc:
        logger.warning("GraphQL enrichment transport error (%s); skipping.", exc)
        return None
    finally:
        # Restore default timeout
        if conn.sock is not None:
            conn.sock.settimeout(config.timeout)

    if resp.status >= 400:
        logger.warning("GraphQL enrichment returned %d; skipping.", resp.status)
        return None

    try:
        data = json.loads(resp_body.decode("utf-8"))
    except Exception:
        logger.warning("GraphQL enrichment response was not valid JSON; skipping.")
        return None

    top_data = data.get("data")
    if top_data is None:
        errors = data.get("errors", [])
        logger.warning(
            "GraphQL enrichment returned null data (errors=%r); skipping.", errors
        )
        return None

    return top_data


# ── Merge logic ──────────────────────────────────────────────────────────────


def _normalise_logical_table_id(value: str | None) -> str | None:
    """Treat empty strings as ``None`` for grouping."""
    if value is None or value == "":
        return None
    return value


def _build_datasource_model(raw: dict[str, Any] | None) -> DatasourceModel | None:
    """Parse a raw VDS getDatasourceModel response into ``DatasourceModel``."""
    if raw is None:
        return None

    tables_raw = raw.get("logicalTables", [])
    relationships_raw = raw.get("logicalTableRelationships", [])

    tables = [
        LogicalTable(
            logical_table_id=t.get("logicalTableId", ""),
            caption=t.get("caption", ""),
            description=t.get("description"),
        )
        for t in tables_raw
    ]

    relationships = []
    for r in relationships_raw:
        from_table = r.get("fromLogicalTable", {})
        to_table = r.get("toLogicalTable", {})
        relationships.append(
            LogicalTableRelationship(
                from_table_id=from_table.get("logicalTableId", ""),
                to_table_id=to_table.get("logicalTableId", ""),
                expression=r.get("expression", {}),
            )
        )

    return DatasourceModel(
        logical_tables=tables,
        logical_table_relationships=relationships,
    )


def _combine_fields(
    read_metadata_data: dict[str, Any],
    datasource_model_data: dict[str, Any] | None,
    graphql_data: dict[str, Any] | None,
    luid: str,
) -> DatasourceSchema:
    """Merge VDS readMetadata, optional datasourceModel, and optional GraphQL enrichment.

    Follows the 7-step procedure from INTROSPECT_DATASOURCE.md §2D.
    """
    # Step 1: Initialise result
    datasource_name: str | None = None
    datasource_description: str | None = None
    graphql_fields_by_name: dict[str, dict[str, Any]] = {}

    if graphql_data is not None:
        published = graphql_data.get("publishedDatasources", [])
        if published:
            ds_info = published[0]
            datasource_name = ds_info.get("name")
            datasource_description = ds_info.get("description")
            for f in ds_info.get("fields", []):
                name = f.get("name")
                if name:
                    graphql_fields_by_name[name] = f

    # Step 2-4: Base fields from readMetadata, enrich from GraphQL
    vds_fields_raw = read_metadata_data.get("data", [])
    field_meta_list: list[FieldMeta] = []
    for vf in vds_fields_raw:
        caption = vf.get("fieldCaption", "")
        gf = graphql_fields_by_name.get(caption)

        field_meta_list.append(
            FieldMeta(
                name=caption,
                data_type=vf.get("dataType", ""),
                column_class=vf.get("columnClass", ""),
                logical_table_id=_normalise_logical_table_id(vf.get("logicalTableId")),
                default_aggregation=vf.get("defaultAggregation"),
                formula=vf.get("formula"),
                description=gf.get("description") if gf else None,
                data_category=gf.get("dataCategory") if gf else None,
                semantic_role=gf.get("semanticRole") if gf else None,
            )
        )

    # Step 5: Populate parameters
    extra_data = read_metadata_data.get("extraData", {})
    params_raw = extra_data.get("parameters", [])
    parameters: list[DatasourceParameter] = []
    for p in params_raw:
        if isinstance(p, dict):
            parameters.append(_parse_parameter(p))

    # Step 6: Group fields by logicalTableId
    table_captions: dict[str | None, str | None] = {}
    if datasource_model_data is not None:
        for t in datasource_model_data.get("logicalTables", []):
            tid = _normalise_logical_table_id(t.get("logicalTableId"))
            table_captions[tid] = t.get("caption")

    groups: dict[str | None, list[FieldMeta]] = {}
    for fm in field_meta_list:
        tid = fm.logical_table_id
        groups.setdefault(tid, []).append(fm)

    field_groups = [
        FieldGroup(
            logical_table_id=tid,
            logical_table_caption=table_captions.get(tid),
            fields=fields,
        )
        for tid, fields in groups.items()
    ]

    # Step 7: Include datasourceModel if available
    datasource_model = _build_datasource_model(datasource_model_data)

    return DatasourceSchema(
        luid=luid,
        name=datasource_name,
        description=datasource_description,
        datasource_model=datasource_model,
        field_groups=field_groups,
        parameters=parameters,
    )


# ── Public API ───────────────────────────────────────────────────────────────


def introspect(
    config: SdkConfig,
    token: AuthToken,
    luid: str,
    conn: http.client.HTTPSConnection | None = None,
) -> DatasourceSchema:
    """Retrieve comprehensive, merged metadata for a single datasource.

    Orchestrates three API calls with strict fallback:

    1. **VDS ``readMetadata``** — primary source of truth. Non-2xx is fatal.
    2. **VDS ``getDatasourceModel``** — logical tables + relationships.
       Unavailable on Tableau < 2025.3; 404 or any non-2xx skips gracefully.
    3. **Metadata API GraphQL** — field enrichment (descriptions,
       data categories, semantic roles). Any failure skips gracefully.

    The merge logic (INTROSPECT_DATASOURCE.md §2D):

    - Only fields from ``readMetadata`` appear in output.
    - Enrichment is applied where ``GraphQL.name == VDS.fieldCaption``.
    - Fields are grouped by ``logicalTableId``.
    - Parameters are extracted from ``extraData.parameters`` and typed.

    Args:
        config: SDK configuration (server URL, API versions, etc.).
        token: Active ``AuthToken`` from ``auth.sign_in``.
        luid: Datasource LUID to introspect.
        conn: Optional ``http.client.HTTPSConnection`` for connection reuse.

    Returns:
        ``DatasourceSchema`` with grouped fields, typed parameters, and
        optional logical-table model.

    Raises:
        IntrospectionError: When ``readMetadata`` returns a non-2xx status
            code, times out, or returns unparseable JSON.
    """
    should_close = conn is None
    conn = conn or _make_connection(config)

    try:
        # Step 2A: readMetadata (fatal on failure)
        read_metadata_data = _call_read_metadata(config, token, conn, luid)

        # Step 2B: getDatasourceModel (skip on any non-2xx, especially 404)
        datasource_model_data = _call_get_datasource_model(config, token, conn, luid)

        # Step 2C: GraphQL enrichment (skip on any failure)
        graphql_data = _call_graphql_enrichment(config, token, conn, luid)

        # Step 2D: Merge
        return _combine_fields(
            read_metadata_data,
            datasource_model_data,
            graphql_data,
            luid,
        )
    finally:
        if should_close:
            conn.close()
